//common use
export const CHANGE_CURRENT_STEP = 'CHANGE_CURRENT_STEP';
export const INITIAL_APP_DATA = 'INITIAL_APP_DATA';
export const INITIAL_FORM_DATA = 'INITIAL_FORM_DATA';
export const SET_ERROR_CONTENT_MESSAGE = 'SET_ERROR_CONTENT_MESSAGE';
export const SET_INLINE_ERROR_MESSAGE = 'SET_INLINE_ERROR_MESSAGE';
export const SET_APP_LOADING_STATUS = 'SET_APP_LOADING_STATUS';
export const SET_APP_PROCESSING_STATUS = 'SET_APP_PROCESSING_STATUS';
export const SET_CURRENT_SECTION = 'SET_CURRENT_SECTION';
export const SET_MYINFO_FLOW_STATUS = 'SET_MYINFO_FLOW_STATUS';
export const SET_HELP_MESSAGE_EXPANDED = 'SET_HELP_MESSAGE_EXPANDED';
export const SET_APPLICATION_REFERENCE_NO = 'SET_APPLICATION_REFERENCE_NO';
export const SET_ERROR_MESSAGE_INPUT = 'SET_ERROR_MESSAGE_INPUT';
export const CLEAR_ERROR_MESSAGE_INPUT = 'CLEAR_ERROR_MESSAGE_INPUT';
export const SET_IDENTIFIER = 'SET_IDENTIFIER';
export const STORE_MY_INFO_DATA = 'STORE_MY_INFO_DATA';
export const SET_PARAMETER = 'SET_PARAMETER';
export const STORE_AGENT_PARAMS = 'STORE_AGENT_PARAMS';

//Application
export const RETRIEVE_APPLICATION = 'RETRIEVE_APPLICATION';
export const SET_IS_PREVIOUS_APPLICATION = 'SET_IS_PREVIOUS_APPLICATION';
export const SET_APPLICATION_DATA_LOADED = 'SET_APPLICATION_DATA_LOADED';
export const RETRIEVING_MYINFO_DATA = 'RETRIEVING_MYINFO_DATA';
export const SET_APPLICATION_ID = 'SET_APPLICATION_ID';
export const SET_ERROR_MESSAGE_WITH_ERRORCODE = 'SET_ERROR_MESSAGE_WITH_ERRORCODE';
export const SET_WITH_APPLICATION_ID = 'SET_WITH_APPLICATION_ID';
export const IS_TAKE_PREVIOUS_APPLCIATION = 'IS_TAKE_PREVIOUS_APPLCIATION';

//set data
export const MYINFO_SET_BASIC_DETAIL_DATA = 'MYINFO_SET_BASIC_DETAIL_DATA';
export const MYINFO_SET_PERSONAL_DETAIL_DATA = 'MYINFO_SET_PERSONAL_DETAIL_DATA';
export const MYINFO_SET_RESIDENTIAL_DETAIL_DATA = 'MYINFO_SET_RESIDENTIAL_DETAIL_DATA';
export const MYINFO_SET_RESIDENTIAL_DETAIL_MAILING_DATA = 'MYINFO_SET_RESIDENTIAL_DETAIL_MAILING_DATA';
export const MYINFO_SET_WORK_DETAIL_DATA = 'MYINFO_SET_WORK_DETAIL_DATA';
export const MYINFO_SET_WORK_NAME_OF_EMPLOYER = 'MYINFO_SET_WORK_NAME_OF_EMPLOYER';
export const SET_LOAN_DETAILS_DATA = 'SET_LOAN_DETAILS_DATA';
export const SET_LOAN_DETAILS_JOINT_APPLICANT_DATA = 'SET_LOAN_DETAILS_JOINT_APPLICANT_DATA';
export const SET_LOAN_DETAILS_ADDITIONAL_DETAILS_DATA = 'SET_LOAN_DETAILS_ADDITIONAL_DETAILS_DATA';
export const SET_WORK_DETAILS_PREVIOUS_DATA = 'SET_WORK_DETAILS_PREVIOUS_DATA';

//local address input
export const LOCAL_ADDRESS_INPUT_CHANGE = 'LOCAL_ADDRESS_INPUT_CHANGE';
export const LOCAL_ADDRESS_INPUT_AUTO_FILL_IN = 'LOCAL_ADDRESS_INPUT_AUTO_FILL_IN';
export const LOCAL_ADDRESS_INPUT_AUTO_FILL_IN_FAIL = 'LOCAL_ADDRESS_INPUT_AUTO_FILL_IN_FAIL';
export const LOCAL_ADDRESS_INPUT_RESET_AUTO_FILL_IN_STATUS = 'LOCAL_ADDRESS_INPUT_RESET_AUTO_FILL_IN_STATUS';
export const LOCAL_ADDRESS_INPUT_SERVICE_DOWN = 'LOCAL_ADDRESS_INPUT_SERVICE_DOWN';
export const LOCAL_ADDRESS_SET_TEXT_INPUT_REQUIRED_ERROR = 'LOCAL_ADDRESS_SET_TEXT_INPUT_REQUIRED_ERROR';
export const LOCAL_ADDRESS_MYINFO_SET_DATA = 'LOCAL_ADDRESS_MYINFO_SET_DATA';
export const MAILING_ADDRESS_MYINFO_SET_DATA = 'MAILING_ADDRESS_MYINFO_SET_DATA';
export const IS_GETTING_LOCAL_ADDRESS = 'IS_GETTING_LOCAL_ADDRESS';
export const LOCAL_ADDRESS_SET_NOT_REQUIRED = 'LOCAL_ADDRESS_SET_NOT_REQUIRED';

//verifyPage
export const SET_DEFAULT_VERIFY_ERROR_CODE = 'SET_DEFAULT_VERIFY_ERROR_CODE';
export const IS_FROM_AGENT_FLOW = 'IS_FROM_AGENT_FLOW';

//basic details
export const BASICDETAILS_HANDLE_TEXT_INPUT_CHANGE = 'BASICDETAILS_HANDLE_TEXT_INPUT_CHANGE';
export const BASIC_DETAILS_UPDATE_OBJECT = 'BASIC_DETAILS_UPDATE_OBJECT';

//otpPage
export const OTP_SET_COUNT_DOWN_STATUS = 'OTP_SET_COUNT_DOWN_STATUS';
export const OTP_SET_PREFIX = 'OTP_SET_PREFIX';
export const OTP_SET_TRIED_COUNT = 'OTP_SET_TRIED_COUNT';
export const OTP_INPUT_CHANGE = 'OTP_INPUT_CHANGE';
export const OTP_IS_SENDING_OTP = 'OTP_IS_SENDING_OTP';
export const RESET_OTP_CODE_TO_EMPTY = 'RESET_OTP_CODE_TO_EMPTY';
export const SET_OTP_VERIFIED = 'SET_OTP_VERIFIED'

//personal details
export const PERSONALDETAILS_TEXT_INPUT_CHANGE = 'PERSONALDETAILS_TEXT_INPUT_CHANGE';
export const PERSONALDETAILS_DROPDOWN_FOCUS = 'PERSONALDETAILS_DROPDOWN_FOCUS';
export const PERSONALDETAILS_DROPDOWN_ITEM_SELECT = 'PERSONALDETAILS_DROPDOWN_ITEM_SELECT';
export const PERSONALDETAILS_DROPDOWN_SEARCH_INPUT_CHANGE = 'PERSONALDETAILS_DROPDOWN_SEARCH_INPUT_CHANGE';
export const PERSONALDETAILS_CHANGE_GENDER_OPTION = 'PERSONALDETAILS_CHANGE_GENDER_OPTION';
export const PERSONALDETAILS_SET_PERSONAL_GENDER_OPTION_ERROR = 'PERSONALDETAILS_SET_PERSONAL_GENDER_OPTION_ERROR';
export const PERSONALDETAILS_PREVIOUS_DATA = 'PERSONALDETAILS_PREVIOUS_DATA';
export const SET_TOGGLE_OPTION = 'SET_TOGGLE_OPTION';
export const CLEAR_ADDITIONAL_ID = 'CLEAR_ADDITIONAL_ID';

//loan details
export const LOANDETAILS_BUTTON_OPTION_CHANGE = 'LOANDETAILS_BUTTON_OPTION_CHANGE';
export const LOANDETAILS_DROPDOWN_FOCUS = 'LOANDETAILS_DROPDOWN_FOCUS';
export const LOANDETAILS_DROPDOWN_ITEM_SELECT = 'LOANDETAILS_DROPDOWN_ITEM_SELECT';
export const LOANDETAILS_DROPDOWN_SEARCH_INPUT_CHANGE = 'LOANDETAILS_DROPDOWN_SEARCH_INPUT_CHANGE';
export const LOANDETAILS_TEXT_INPUT_CHANGE = 'LOANDETAILS_TEXT_INPUT_CHANGE';
export const LOANDETAILS_IS_TOGGLE = 'LOANDETAILS_IS_TOGGLE';
export const LOANDETAILS_SET_BUTTON_OPTION_ERROR = 'LOANDETAILS_SET_BUTTON_OPTION_ERROR';
export const LOANDETAILS_SET_LOAN_AMOUNT_VALUE = 'LOANDETAILS_SET_LOAN_AMOUNT_VALUE';
export const LOANDETAILS_CLEAR_LOAN_AMOUNT_VALUE = 'LOANDETAILS_CLEAR_LOAN_AMOUNT_VALUE';
export const LOANDETAILS_CLEAR_LOAN_MAX_AMOUNT_VALUE = 'LOANDETAILS_CLEAR_LOAN_MAX_AMOUNT_VALUE';
export const LOANDETAILS_SET_MUTIPLE_SECTION_VALUE = 'LOANDETAILS_SET_MUTIPLE_SECTION_VALUE';
export const LOANDETAILS_MULTIPLE_BUTTON_OPTION_CHANGE = 'LOANDETAILS_MULTIPLE_BUTTON_OPTION_CHANGE';
export const LOANDETAILS_DELETE_MULTIPLE_BUTTON_OPTION_CHANGE = 'LOANDETAILS_DELETE_MULTIPLE_BUTTON_OPTION_CHANGE';
export const LOANDETAILS_SET_DATE_OF_TOP = 'LOANDETAILS_SET_DATE_OF_TOP';
export const LOANDETAILS_RADIO_OPTION_CHANGE = 'LOANDETAILS_RADIO_OPTION_CHANGE';
export const STORE_LOAN_PACKAGE = 'STORE_LOAN_PACKAGE';
export const SET_FILTERED_LOAN_PACKAGE = 'SET_FILTERED_LOAN_PACKAGE';
export const SET_SLIDER_ERROR = 'SET_SLIDER_ERROR';
export const CLEAR_SLIDER_ERROR = 'CLEAR_SLIDER_ERROR';
export const SET_DEFAULT_LOAN_PACKAGE = 'SET_DEFAULT_LOAN_PACKAGE';
export const CLEAR_SELECTED_LOAN_PACKAGE = 'CLEAR_SELECTED_LOAN_PACKAGE';

//residential details
export const RESIDENTIALDETAILS_IS_TOGGLED = 'RESIDENTIALDETAILS_IS_TOGGLED';
export const RESIDENTIALDETAILS_DROPDOWN_ITEM_SELECT = 'RESIDENTIALDETAILS_DROPDOWN_ITEM_SELECT';
export const RESIDENTIALDETAILS_DROPDOWN_SEARCH_INPUT_CHANGE = 'RESIDENTIALDETAILS_DROPDOWN_SEARCH_INPUT_CHANGE';
export const RESIDENTIALDETAILS_DROPDOWN_FOCUS = 'RESIDENTIALDETAILS_DROPDOWN_FOCUS';
export const RESIDENTIALDETAILS_TEXT_INPUT_CHANGE = 'RESIDENTIALDETAILS_TEXT_INPUT_CHANGE';

//work Details
export const WORK_DETAILS_SET_TEXT_INPUT_REQUIRED_ERROR = 'WORK_DETAILS_SET_TEXT_INPUT_REQUIRED_ERROR';
export const WORK_DROPDOWN_FOCUS = 'WORK_DROPDOWN_FOCUS';
export const WORK_DROPDOWN_ITEM_SELECT = 'WORK_DROPDOWN_ITEM_SELECT';
export const WORK_DROPDOWN_SEARCH_INPUT_CHANGE = 'WORK_DROPDOWN_SEARCH_INPUT_CHANGE';
export const WORK_TEXT_INPUT_CHANGE = 'WORK_TEXT_INPUT_CHANGE';
export const WORK_SET_CPF_TABLE_EXPANDED_ROW = 'WORK_sET_CPF_TABLE_EXPANDED_ROW';
export const WORK_DETAILS_SET_DROPDOWN_ERROR = 'WORK_DETAILS_SET_DROPDOWN_ERROR';
export const WORK_IS_TOGGLED = 'WORK_IS_TOGGLED';
export const WORK_DETAILS_SET_TOGGLE_ERROR = 'WORK_DETAILS_SET_TOGGLE_ERROR';
export const WORK_DETAILS_SET_WORKING_SG = 'WORK_DETAILS_SET_WORKING_SG';
export const WORK_DETAILS_SET_TOGGLE = "WORK_DETAILS_SET_TOGGLE";

//Confirm details
export const CONFIRMDETAILS_IS_TOGGLED = 'CONFIRMDETAILS_IS_TOGGLED';
export const CONFIRMDETAILS_SET_TOGGLE_ERROR_MESSAGE = 'CONFIRMDETAILS_SET_TOGGLE_ERROR_MESSAGE';

//upload Documents
export const FILEUPLOAD_UPDATE_UPLOADING_PROGRESS = 'FILEUPLOAD_UPDATE_UPLOADING_PROGRESS';
export const FILEUPLOAD_RECEIVED_UPLOADED_FILE = 'FILEUPLOAD_RECEIVED_UPLOADED_FILE';
export const FILEUPLOAD_SET_ERROR_MESSAGE = 'FILEUPLOAD_SET_ERROR_MESSAGE';
export const FILEUPLOAD_UPDATE_TOGGLE_STATUS = 'FILEUPLOAD_UPDATE_TOGGLE_STATUS';
export const FILEUPLOAD_RESET_UPLOAD_STATUS = 'FILEUPLOAD_RESET_UPLOAD_STATUS';
export const FILEUPLOAD_TEXT_INPUT_CHANGE = 'FILEUPLOAD_TEXT_INPUT_CHANGE';
export const FILEUPLOAD_SET_TEXT_INPUT_REQUIRED_ERROR = 'FILEUPLOAD_SET_TEXT_INPUT_REQUIRED_ERROR';
export const SHOW_UPLOAD_DOCUMENT = 'SHOW_UPLOAD_DOCUMENT';
export const SET_PREVIOUS_UPLOAD_DOCUMENTS = 'SET_PREVIOUS_UPLOAD_DOCUMENTS';

// verify
export const SET_EMAIL_VERIFY_STATUS = 'SET_EMAIL_VERIFY_STATUS';
export const SET_ERROR_MESSAGE_WITH_PARAMTER = 'SET_ERROR_MESSAGE_WITH_PARAMTER';
export const SET_EMAIL_VERIFYING_STATUS = 'SET_EMAIL_VERIFYING_STATUS';
export const SET_VERIFY_CODE = 'SET_VERIFY_CODE';
export const STORE_REDIRECT_URL = 'STORE_REDIRECT_URL';
export const APPEND_PARAMETER_TO_URL = 'APPEND_PARAMETER_TO_URL';
