//common use
export const INITIAL_APP_DATA = 'INITIAL_APP_DATA';
export const INITIAL_APP_MSG = 'INITIAL_APP_MSG';
export const INITIAL_APP_INPUT_DATA = 'INITIAL_APP_INPUT_DATA';
export const GET_DATA_INFO = 'GET_DATA_INFO';
export const SET_APP_LOADING_STATUS = 'SET_APP_LOADING_STATUS';
export const SET_ERROR_CONTENT_MESSAGE = 'SET_ERROR_CONTENT_MESSAGE';
export const SET_INLINE_ERROR_MESSAGE = 'SET_INLINE_ERROR_MESSAGE';
export const RESET_STATE = 'RESET_STATE';
export const RESET_TO_INITIAL = 'RESET_TO_INITIAL';

